/* Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "Statechart.h"
#include "Statechart_required.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_main_region_Vykdymas_r1_SampleRequestedADC(Statechart* handle);
static void enact_main_region_Vykdymas_r1_SampleReadingADC(Statechart* handle);
static void enact_main_region_Vykdymas_r1_Processing(Statechart* handle);
static void enact_main_region_Vykdymas_r2_LCD_Send(Statechart* handle);
static void enact_main_region_Vykdymas_r3_UART_Send(Statechart* handle);
static void enact_main_region_Vykdymas_r4_Check_Buttons(Statechart* handle);
static void enact_main_region_Start(Statechart* handle);
static void exact_main_region_Vykdymas_r1_SampleReadingADC(Statechart* handle);
static void exact_main_region_Vykdymas_r1_Processing(Statechart* handle);
static void enseq_main_region_Vykdymas_r1_WaitSamplePeriod_default(Statechart* handle);
static void enseq_main_region_Vykdymas_r1_SampleRequestedADC_default(Statechart* handle);
static void enseq_main_region_Vykdymas_r1_SampleReadingADC_default(Statechart* handle);
static void enseq_main_region_Vykdymas_r1_Processing_default(Statechart* handle);
static void enseq_main_region_Vykdymas_r2_LCD_Send_default(Statechart* handle);
static void enseq_main_region_Vykdymas_r2_LCD_default(Statechart* handle);
static void enseq_main_region_Vykdymas_r3_UART_default(Statechart* handle);
static void enseq_main_region_Vykdymas_r3_UART_Send_default(Statechart* handle);
static void enseq_main_region_Vykdymas_r4_Button_default(Statechart* handle);
static void enseq_main_region_Vykdymas_r4_Check_Buttons_default(Statechart* handle);
static void enseq_main_region_Start_default(Statechart* handle);
static void enseq_main_region_default(Statechart* handle);
static void exseq_main_region_Vykdymas_r1_WaitSamplePeriod(Statechart* handle);
static void exseq_main_region_Vykdymas_r1_SampleRequestedADC(Statechart* handle);
static void exseq_main_region_Vykdymas_r1_SampleReadingADC(Statechart* handle);
static void exseq_main_region_Vykdymas_r1_Processing(Statechart* handle);
static void exseq_main_region_Vykdymas_r2_LCD_Send(Statechart* handle);
static void exseq_main_region_Vykdymas_r2_LCD(Statechart* handle);
static void exseq_main_region_Vykdymas_r3_UART(Statechart* handle);
static void exseq_main_region_Vykdymas_r3_UART_Send(Statechart* handle);
static void exseq_main_region_Vykdymas_r4_Button(Statechart* handle);
static void exseq_main_region_Vykdymas_r4_Check_Buttons(Statechart* handle);
static void exseq_main_region_Start(Statechart* handle);
static void exseq_main_region(Statechart* handle);
static void react_main_region__entry_Default(Statechart* handle);

/*! The reactions of state Vykdymas. */
static sc_integer main_region_Vykdymas_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state WaitSamplePeriod. */
static sc_integer main_region_Vykdymas_r1_WaitSamplePeriod_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state SampleRequestedADC. */
static sc_integer main_region_Vykdymas_r1_SampleRequestedADC_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state SampleReadingADC. */
static sc_integer main_region_Vykdymas_r1_SampleReadingADC_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Processing. */
static sc_integer main_region_Vykdymas_r1_Processing_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state LCD_Send. */
static sc_integer main_region_Vykdymas_r2_LCD_Send_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state LCD. */
static sc_integer main_region_Vykdymas_r2_LCD_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state UART. */
static sc_integer main_region_Vykdymas_r3_UART_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state UART_Send. */
static sc_integer main_region_Vykdymas_r3_UART_Send_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Button. */
static sc_integer main_region_Vykdymas_r4_Button_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Check_Buttons. */
static sc_integer main_region_Vykdymas_r4_Check_Buttons_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state Start. */
static sc_integer main_region_Start_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);




static void statechart_internal_set_sample_no(Statechart* handle, sc_integer value)
;


static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	/* Default init sequence for statechart Statechart */
	statechart_internal_set_sample_no(handle, 0);
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_main_region_default(handle);
	handle->doCompletion = bool_false;
	do
	{ 
		if (handle->completed == bool_true)
		{ 
			handle->doCompletion = bool_true;
		} 
		handle->completed = bool_false;
		micro_step(handle);
		clear_in_events(handle);
		handle->doCompletion = bool_false;
	} while (handle->completed == bool_true);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_main_region(handle);
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVector[1] = Statechart_last_state;
	handle->stateConfVector[2] = Statechart_last_state;
	handle->stateConfVector[3] = Statechart_last_state;
	handle->stateConfVectorPosition = 3;
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_main_region_Vykdymas :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS] >= Statechart_main_region_Vykdymas
				&& handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS] <= Statechart_main_region_Vykdymas_r4_Check_Buttons);
				break;
		case Statechart_main_region_Vykdymas_r1_WaitSamplePeriod :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R1_WAITSAMPLEPERIOD] == Statechart_main_region_Vykdymas_r1_WaitSamplePeriod
			);
				break;
		case Statechart_main_region_Vykdymas_r1_SampleRequestedADC :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R1_SAMPLEREQUESTEDADC] == Statechart_main_region_Vykdymas_r1_SampleRequestedADC
			);
				break;
		case Statechart_main_region_Vykdymas_r1_SampleReadingADC :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R1_SAMPLEREADINGADC] == Statechart_main_region_Vykdymas_r1_SampleReadingADC
			);
				break;
		case Statechart_main_region_Vykdymas_r1_Processing :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R1_PROCESSING] == Statechart_main_region_Vykdymas_r1_Processing
			);
				break;
		case Statechart_main_region_Vykdymas_r2_LCD_Send :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R2_LCD_SEND] == Statechart_main_region_Vykdymas_r2_LCD_Send
			);
				break;
		case Statechart_main_region_Vykdymas_r2_LCD :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R2_LCD] == Statechart_main_region_Vykdymas_r2_LCD
			);
				break;
		case Statechart_main_region_Vykdymas_r3_UART :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R3_UART] == Statechart_main_region_Vykdymas_r3_UART
			);
				break;
		case Statechart_main_region_Vykdymas_r3_UART_Send :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R3_UART_SEND] == Statechart_main_region_Vykdymas_r3_UART_Send
			);
				break;
		case Statechart_main_region_Vykdymas_r4_Button :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R4_BUTTON] == Statechart_main_region_Vykdymas_r4_Button
			);
				break;
		case Statechart_main_region_Vykdymas_r4_Check_Buttons :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R4_CHECK_BUTTONS] == Statechart_main_region_Vykdymas_r4_Check_Buttons
			);
				break;
		case Statechart_main_region_Start :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_MAIN_REGION_START] == Statechart_main_region_Start
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
	}

static void clear_in_events(Statechart* handle)
{
	handle->iface.Ev_GetSample_raised = bool_false;
	handle->iface.Ev_ADCSampleReady_raised = bool_false;
	handle->iface.Ev_SendUart_raised = bool_false;
	handle->iface.Ev_DisplayLCD_raised = bool_false;
	handle->iface.Ev_Button_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
 			sc_integer transitioned = -1;
	handle->stateConfVectorPosition = 0;
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_Vykdymas_r1_WaitSamplePeriod :
		{
			transitioned = main_region_Vykdymas_r1_WaitSamplePeriod_react(handle,transitioned);
			break;
		}
		case Statechart_main_region_Vykdymas_r1_SampleRequestedADC :
		{
			transitioned = main_region_Vykdymas_r1_SampleRequestedADC_react(handle,transitioned);
			break;
		}
		case Statechart_main_region_Vykdymas_r1_SampleReadingADC :
		{
			transitioned = main_region_Vykdymas_r1_SampleReadingADC_react(handle,transitioned);
			break;
		}
		case Statechart_main_region_Vykdymas_r1_Processing :
		{
			transitioned = main_region_Vykdymas_r1_Processing_react(handle,transitioned);
			break;
		}
		case Statechart_main_region_Start :
		{
			transitioned = main_region_Start_react(handle,transitioned);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	if ((handle->stateConfVectorPosition) < (1))
	{ 
		switch(handle->stateConfVector[ 1 ])
		{
			case Statechart_main_region_Vykdymas_r2_LCD_Send :
			{
				transitioned = main_region_Vykdymas_r2_LCD_Send_react(handle,transitioned);
				break;
			}
			case Statechart_main_region_Vykdymas_r2_LCD :
			{
				transitioned = main_region_Vykdymas_r2_LCD_react(handle,transitioned);
				break;
			}
			default: 
				/* do nothing */
				break;
		}
	} if ((handle->stateConfVectorPosition) < (2))
	{ 
		switch(handle->stateConfVector[ 2 ])
		{
			case Statechart_main_region_Vykdymas_r3_UART :
			{
				transitioned = main_region_Vykdymas_r3_UART_react(handle,transitioned);
				break;
			}
			case Statechart_main_region_Vykdymas_r3_UART_Send :
			{
				transitioned = main_region_Vykdymas_r3_UART_Send_react(handle,transitioned);
				break;
			}
			default: 
				/* do nothing */
				break;
		}
	} if ((handle->stateConfVectorPosition) < (3))
	{ 
		switch(handle->stateConfVector[ 3 ])
		{
			case Statechart_main_region_Vykdymas_r4_Button :
			{
				main_region_Vykdymas_r4_Button_react(handle,transitioned);
				break;
			}
			case Statechart_main_region_Vykdymas_r4_Check_Buttons :
			{
				main_region_Vykdymas_r4_Check_Buttons_react(handle,transitioned);
				break;
			}
			default: 
				/* do nothing */
				break;
		}
	} 
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		handle->doCompletion = bool_false;
		do
		{ 
			if (handle->completed == bool_true)
			{ 
				handle->doCompletion = bool_true;
			} 
			handle->completed = bool_false;
			micro_step(handle);
			clear_in_events(handle);
			handle->doCompletion = bool_false;
		} while (handle->completed == bool_true);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_raise_ev_GetSample(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Ev_GetSample);
	run_cycle(handle);
}

void statechart_raise_ev_ADCSampleReady(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Ev_ADCSampleReady);
	run_cycle(handle);
}

void statechart_raise_ev_SendUart(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Ev_SendUart);
	run_cycle(handle);
}

void statechart_raise_ev_DisplayLCD(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Ev_DisplayLCD);
	run_cycle(handle);
}

void statechart_raise_ev_Button(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_Ev_Button);
	run_cycle(handle);
}




static void statechart_internal_set_sample_no(Statechart* handle, sc_integer value)
{
	handle->internal.sample_no = value;
}


/* implementations of all internal functions */

/* Entry action for state 'SampleRequestedADC'. */
static void enact_main_region_Vykdymas_r1_SampleRequestedADC(Statechart* handle)
{
	/* Entry action for state 'SampleRequestedADC'. */
	statechart_startConvADC(handle);
}

static void enact_main_region_Vykdymas_r1_SampleReadingADC(Statechart* handle)
{
	/* Entry action for state 'SampleReadingADC'. */
	statechart_readADCSample(handle,0);
	handle->completed = bool_true;
}

static void enact_main_region_Vykdymas_r1_Processing(Statechart* handle)
{
	/* Entry action for state 'Processing'. */
	statechart_processData(handle);
	handle->completed = bool_true;
}

static void enact_main_region_Vykdymas_r2_LCD_Send(Statechart* handle)
{
	/* Entry action for state 'LCD_Send'. */
	statechart_displayInfo(handle);
	handle->completed = bool_true;
}

static void enact_main_region_Vykdymas_r3_UART_Send(Statechart* handle)
{
	/* Entry action for state 'UART_Send'. */
	statechart_sendUART(handle);
	handle->completed = bool_true;
}

static void enact_main_region_Vykdymas_r4_Check_Buttons(Statechart* handle)
{
	/* Entry action for state 'Check_Buttons'. */
	statechart_checkButtons(handle);
	handle->completed = bool_true;
}

static void enact_main_region_Start(Statechart* handle)
{
	handle->completed = bool_true;
}

/* Exit action for state 'SampleReadingADC'. */
static void exact_main_region_Vykdymas_r1_SampleReadingADC(Statechart* handle)
{
	/* Exit action for state 'SampleReadingADC'. */
	statechart_saveADCSample(handle,0, handle->internal.sample_no);
	statechart_internal_set_sample_no(handle, (handle->internal.sample_no + 1));
}

/* Exit action for state 'Processing'. */
static void exact_main_region_Vykdymas_r1_Processing(Statechart* handle)
{
	/* Exit action for state 'Processing'. */
	statechart_internal_set_sample_no(handle, 0);
}

/* 'default' enter sequence for state WaitSamplePeriod */
static void enseq_main_region_Vykdymas_r1_WaitSamplePeriod_default(Statechart* handle)
{
	/* 'default' enter sequence for state WaitSamplePeriod */
	handle->stateConfVector[0] = Statechart_main_region_Vykdymas_r1_WaitSamplePeriod;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state SampleRequestedADC */
static void enseq_main_region_Vykdymas_r1_SampleRequestedADC_default(Statechart* handle)
{
	/* 'default' enter sequence for state SampleRequestedADC */
	enact_main_region_Vykdymas_r1_SampleRequestedADC(handle);
	handle->stateConfVector[0] = Statechart_main_region_Vykdymas_r1_SampleRequestedADC;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state SampleReadingADC */
static void enseq_main_region_Vykdymas_r1_SampleReadingADC_default(Statechart* handle)
{
	/* 'default' enter sequence for state SampleReadingADC */
	enact_main_region_Vykdymas_r1_SampleReadingADC(handle);
	handle->stateConfVector[0] = Statechart_main_region_Vykdymas_r1_SampleReadingADC;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Processing */
static void enseq_main_region_Vykdymas_r1_Processing_default(Statechart* handle)
{
	/* 'default' enter sequence for state Processing */
	enact_main_region_Vykdymas_r1_Processing(handle);
	handle->stateConfVector[0] = Statechart_main_region_Vykdymas_r1_Processing;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state LCD_Send */
static void enseq_main_region_Vykdymas_r2_LCD_Send_default(Statechart* handle)
{
	/* 'default' enter sequence for state LCD_Send */
	enact_main_region_Vykdymas_r2_LCD_Send(handle);
	handle->stateConfVector[1] = Statechart_main_region_Vykdymas_r2_LCD_Send;
	handle->stateConfVectorPosition = 1;
}

/* 'default' enter sequence for state LCD */
static void enseq_main_region_Vykdymas_r2_LCD_default(Statechart* handle)
{
	/* 'default' enter sequence for state LCD */
	handle->stateConfVector[1] = Statechart_main_region_Vykdymas_r2_LCD;
	handle->stateConfVectorPosition = 1;
}

/* 'default' enter sequence for state UART */
static void enseq_main_region_Vykdymas_r3_UART_default(Statechart* handle)
{
	/* 'default' enter sequence for state UART */
	handle->stateConfVector[2] = Statechart_main_region_Vykdymas_r3_UART;
	handle->stateConfVectorPosition = 2;
}

/* 'default' enter sequence for state UART_Send */
static void enseq_main_region_Vykdymas_r3_UART_Send_default(Statechart* handle)
{
	/* 'default' enter sequence for state UART_Send */
	enact_main_region_Vykdymas_r3_UART_Send(handle);
	handle->stateConfVector[2] = Statechart_main_region_Vykdymas_r3_UART_Send;
	handle->stateConfVectorPosition = 2;
}

/* 'default' enter sequence for state Button */
static void enseq_main_region_Vykdymas_r4_Button_default(Statechart* handle)
{
	/* 'default' enter sequence for state Button */
	handle->stateConfVector[3] = Statechart_main_region_Vykdymas_r4_Button;
	handle->stateConfVectorPosition = 3;
}

/* 'default' enter sequence for state Check_Buttons */
static void enseq_main_region_Vykdymas_r4_Check_Buttons_default(Statechart* handle)
{
	/* 'default' enter sequence for state Check_Buttons */
	enact_main_region_Vykdymas_r4_Check_Buttons(handle);
	handle->stateConfVector[3] = Statechart_main_region_Vykdymas_r4_Check_Buttons;
	handle->stateConfVectorPosition = 3;
}

/* 'default' enter sequence for state Start */
static void enseq_main_region_Start_default(Statechart* handle)
{
	/* 'default' enter sequence for state Start */
	enact_main_region_Start(handle);
	handle->stateConfVector[0] = Statechart_main_region_Start;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(Statechart* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state WaitSamplePeriod */
static void exseq_main_region_Vykdymas_r1_WaitSamplePeriod(Statechart* handle)
{
	/* Default exit sequence for state WaitSamplePeriod */
	handle->stateConfVector[0] = Statechart_main_region_Vykdymas;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state SampleRequestedADC */
static void exseq_main_region_Vykdymas_r1_SampleRequestedADC(Statechart* handle)
{
	/* Default exit sequence for state SampleRequestedADC */
	handle->stateConfVector[0] = Statechart_main_region_Vykdymas;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state SampleReadingADC */
static void exseq_main_region_Vykdymas_r1_SampleReadingADC(Statechart* handle)
{
	/* Default exit sequence for state SampleReadingADC */
	handle->stateConfVector[0] = Statechart_main_region_Vykdymas;
	handle->stateConfVectorPosition = 0;
	exact_main_region_Vykdymas_r1_SampleReadingADC(handle);
}

/* Default exit sequence for state Processing */
static void exseq_main_region_Vykdymas_r1_Processing(Statechart* handle)
{
	/* Default exit sequence for state Processing */
	handle->stateConfVector[0] = Statechart_main_region_Vykdymas;
	handle->stateConfVectorPosition = 0;
	exact_main_region_Vykdymas_r1_Processing(handle);
}

/* Default exit sequence for state LCD_Send */
static void exseq_main_region_Vykdymas_r2_LCD_Send(Statechart* handle)
{
	/* Default exit sequence for state LCD_Send */
	handle->stateConfVector[1] = Statechart_main_region_Vykdymas;
	handle->stateConfVectorPosition = 1;
}

/* Default exit sequence for state LCD */
static void exseq_main_region_Vykdymas_r2_LCD(Statechart* handle)
{
	/* Default exit sequence for state LCD */
	handle->stateConfVector[1] = Statechart_main_region_Vykdymas;
	handle->stateConfVectorPosition = 1;
}

/* Default exit sequence for state UART */
static void exseq_main_region_Vykdymas_r3_UART(Statechart* handle)
{
	/* Default exit sequence for state UART */
	handle->stateConfVector[2] = Statechart_main_region_Vykdymas;
	handle->stateConfVectorPosition = 2;
}

/* Default exit sequence for state UART_Send */
static void exseq_main_region_Vykdymas_r3_UART_Send(Statechart* handle)
{
	/* Default exit sequence for state UART_Send */
	handle->stateConfVector[2] = Statechart_main_region_Vykdymas;
	handle->stateConfVectorPosition = 2;
}

/* Default exit sequence for state Button */
static void exseq_main_region_Vykdymas_r4_Button(Statechart* handle)
{
	/* Default exit sequence for state Button */
	handle->stateConfVector[3] = Statechart_main_region_Vykdymas;
	handle->stateConfVectorPosition = 3;
}

/* Default exit sequence for state Check_Buttons */
static void exseq_main_region_Vykdymas_r4_Check_Buttons(Statechart* handle)
{
	/* Default exit sequence for state Check_Buttons */
	handle->stateConfVector[3] = Statechart_main_region_Vykdymas;
	handle->stateConfVectorPosition = 3;
}

/* Default exit sequence for state Start */
static void exseq_main_region_Start(Statechart* handle)
{
	/* Default exit sequence for state Start */
	handle->stateConfVector[0] = Statechart_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region main region */
static void exseq_main_region(Statechart* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of Statechart.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_main_region_Vykdymas_r1_WaitSamplePeriod :
		{
			exseq_main_region_Vykdymas_r1_WaitSamplePeriod(handle);
			break;
		}
		case Statechart_main_region_Vykdymas_r1_SampleRequestedADC :
		{
			exseq_main_region_Vykdymas_r1_SampleRequestedADC(handle);
			break;
		}
		case Statechart_main_region_Vykdymas_r1_SampleReadingADC :
		{
			exseq_main_region_Vykdymas_r1_SampleReadingADC(handle);
			break;
		}
		case Statechart_main_region_Vykdymas_r1_Processing :
		{
			exseq_main_region_Vykdymas_r1_Processing(handle);
			break;
		}
		case Statechart_main_region_Start :
		{
			exseq_main_region_Start(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	/* Handle exit of all possible states (of Statechart.main_region) at position 1... */
	switch(handle->stateConfVector[ 1 ])
	{
		case Statechart_main_region_Vykdymas_r2_LCD_Send :
		{
			exseq_main_region_Vykdymas_r2_LCD_Send(handle);
			break;
		}
		case Statechart_main_region_Vykdymas_r2_LCD :
		{
			exseq_main_region_Vykdymas_r2_LCD(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	/* Handle exit of all possible states (of Statechart.main_region) at position 2... */
	switch(handle->stateConfVector[ 2 ])
	{
		case Statechart_main_region_Vykdymas_r3_UART :
		{
			exseq_main_region_Vykdymas_r3_UART(handle);
			break;
		}
		case Statechart_main_region_Vykdymas_r3_UART_Send :
		{
			exseq_main_region_Vykdymas_r3_UART_Send(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
	/* Handle exit of all possible states (of Statechart.main_region) at position 3... */
	switch(handle->stateConfVector[ 3 ])
	{
		case Statechart_main_region_Vykdymas_r4_Button :
		{
			exseq_main_region_Vykdymas_r4_Button(handle);
			break;
		}
		case Statechart_main_region_Vykdymas_r4_Check_Buttons :
		{
			exseq_main_region_Vykdymas_r4_Check_Buttons(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_Start_default(handle);
}


static sc_integer main_region_Vykdymas_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Vykdymas. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	} return transitioned_after;
}

static sc_integer main_region_Vykdymas_r1_WaitSamplePeriod_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state WaitSamplePeriod. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.Ev_GetSample_raised == bool_true)
			{ 
				exseq_main_region_Vykdymas_r1_WaitSamplePeriod(handle);
				enseq_main_region_Vykdymas_r1_SampleRequestedADC_default(handle);
				transitioned_after = 0;
			} 
		} 
	} return transitioned_after;
}

static sc_integer main_region_Vykdymas_r1_SampleRequestedADC_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SampleRequestedADC. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (0))
		{ 
			if (handle->iface.Ev_ADCSampleReady_raised == bool_true)
			{ 
				exseq_main_region_Vykdymas_r1_SampleRequestedADC(handle);
				enseq_main_region_Vykdymas_r1_SampleReadingADC_default(handle);
				transitioned_after = 0;
			} 
		} 
	} return transitioned_after;
}

static sc_integer main_region_Vykdymas_r1_SampleReadingADC_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state SampleReadingADC. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state SampleReadingADC */
		handle->stateConfVector[0] = Statechart_main_region_Vykdymas;
		handle->stateConfVectorPosition = 0;
		exact_main_region_Vykdymas_r1_SampleReadingADC(handle);
		/* The reactions of state null. */
		if ((handle->internal.sample_no) < (200))
		{ 
			enseq_main_region_Vykdymas_r1_WaitSamplePeriod_default(handle);
		}  else
		{
			enseq_main_region_Vykdymas_r1_Processing_default(handle);
		}
	} 
	return transitioned_after;
}

static sc_integer main_region_Vykdymas_r1_Processing_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Processing. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Processing */
		handle->stateConfVector[0] = Statechart_main_region_Vykdymas;
		handle->stateConfVectorPosition = 0;
		exact_main_region_Vykdymas_r1_Processing(handle);
		/* 'default' enter sequence for state WaitSamplePeriod */
		handle->stateConfVector[0] = Statechart_main_region_Vykdymas_r1_WaitSamplePeriod;
		handle->stateConfVectorPosition = 0;
	} 
	return transitioned_after;
}

static sc_integer main_region_Vykdymas_r2_LCD_Send_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state LCD_Send. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state LCD_Send */
		handle->stateConfVector[1] = Statechart_main_region_Vykdymas;
		handle->stateConfVectorPosition = 1;
		/* 'default' enter sequence for state LCD */
		handle->stateConfVector[1] = Statechart_main_region_Vykdymas_r2_LCD;
		handle->stateConfVectorPosition = 1;
	} 
	return transitioned_after;
}

static sc_integer main_region_Vykdymas_r2_LCD_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state LCD. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (1))
		{ 
			if (handle->iface.Ev_DisplayLCD_raised == bool_true)
			{ 
				exseq_main_region_Vykdymas_r2_LCD(handle);
				enseq_main_region_Vykdymas_r2_LCD_Send_default(handle);
				transitioned_after = 1;
			} 
		} 
	} return transitioned_after;
}

static sc_integer main_region_Vykdymas_r3_UART_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state UART. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (2))
		{ 
			if (handle->iface.Ev_SendUart_raised == bool_true)
			{ 
				exseq_main_region_Vykdymas_r3_UART(handle);
				enseq_main_region_Vykdymas_r3_UART_Send_default(handle);
				transitioned_after = 2;
			} 
		} 
	} return transitioned_after;
}

static sc_integer main_region_Vykdymas_r3_UART_Send_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state UART_Send. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state UART_Send */
		handle->stateConfVector[2] = Statechart_main_region_Vykdymas;
		handle->stateConfVectorPosition = 2;
		/* 'default' enter sequence for state UART */
		handle->stateConfVector[2] = Statechart_main_region_Vykdymas_r3_UART;
		handle->stateConfVectorPosition = 2;
	} 
	return transitioned_after;
}

static sc_integer main_region_Vykdymas_r4_Button_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Button. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_false)
	{ 
		if ((transitioned_after) < (3))
		{ 
			if (handle->iface.Ev_Button_raised == bool_true)
			{ 
				exseq_main_region_Vykdymas_r4_Button(handle);
				enseq_main_region_Vykdymas_r4_Check_Buttons_default(handle);
				main_region_Vykdymas_react(handle,0);
				transitioned_after = 3;
			} 
		} 
		/* If no transition was taken */
		if ((transitioned_after) == (transitioned_before))
		{ 
			/* then execute local reactions. */
			transitioned_after = main_region_Vykdymas_react(handle,transitioned_before);
		} 
	} return transitioned_after;
}

static sc_integer main_region_Vykdymas_r4_Check_Buttons_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Check_Buttons. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Check_Buttons */
		handle->stateConfVector[3] = Statechart_main_region_Vykdymas;
		handle->stateConfVectorPosition = 3;
		/* 'default' enter sequence for state Button */
		handle->stateConfVector[3] = Statechart_main_region_Vykdymas_r4_Button;
		handle->stateConfVectorPosition = 3;
		main_region_Vykdymas_react(handle,0);
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = main_region_Vykdymas_react(handle,transitioned_before);
	}
	return transitioned_after;
}

static sc_integer main_region_Start_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state Start. */
 			sc_integer transitioned_after = transitioned_before;
	if (handle->doCompletion == bool_true)
	{ 
		/* Default exit sequence for state Start */
		handle->stateConfVector[0] = Statechart_last_state;
		handle->stateConfVectorPosition = 0;
		/* The reactions of state null. */
		enseq_main_region_Vykdymas_r1_WaitSamplePeriod_default(handle);
		enseq_main_region_Vykdymas_r2_LCD_default(handle);
		enseq_main_region_Vykdymas_r3_UART_default(handle);
		enseq_main_region_Vykdymas_r4_Button_default(handle);
	}  else
	{
		/* Always execute local reactions. */
		transitioned_after = transitioned_before;
	}
	return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_Ev_GetSample:
		{
			handle->iface.Ev_GetSample_raised = bool_true;
			return bool_true;
		}
		case Statechart_Ev_ADCSampleReady:
		{
			handle->iface.Ev_ADCSampleReady_raised = bool_true;
			return bool_true;
		}
		case Statechart_Ev_SendUart:
		{
			handle->iface.Ev_SendUart_raised = bool_true;
			return bool_true;
		}
		case Statechart_Ev_DisplayLCD:
		{
			handle->iface.Ev_DisplayLCD_raised = bool_true;
			return bool_true;
		}
		case Statechart_Ev_Button:
		{
			handle->iface.Ev_Button_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
