/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_H_
#define STATECHART_H_

#ifdef __cplusplus
extern "C" { 
#endif

/*!
* Forward declaration for the Statechart state machine.
*/
typedef struct Statechart Statechart;

/*!
* Forward declaration of the data structure for the StatechartIface interface scope.
*/
typedef struct StatechartIface StatechartIface;

/*!
* Forward declaration of the data structure for the StatechartInternal interface scope.
*/
typedef struct StatechartInternal StatechartInternal;

#ifdef __cplusplus
}
#endif

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" { 
#endif 

/*! \file
Header of the state machine 'Statechart'.
*/

#ifndef STATECHART_EVENTQUEUE_BUFFERSIZE
#define STATECHART_EVENTQUEUE_BUFFERSIZE 20
#endif
#ifndef STATECHART_IN_EVENTQUEUE_BUFFERSIZE
#define STATECHART_IN_EVENTQUEUE_BUFFERSIZE STATECHART_EVENTQUEUE_BUFFERSIZE
#endif
#ifndef SC_INVALID_EVENT_VALUE
#define SC_INVALID_EVENT_VALUE 0
#endif
/*! Define number of states in the state enum */
#define STATECHART_STATE_COUNT 12

/*! Define dimension of the state configuration vector for orthogonal states. */
#define STATECHART_MAX_ORTHOGONAL_STATES 4

/*! Define indices of states in the StateConfVector */
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS 0
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R1_WAITSAMPLEPERIOD 0
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R1_SAMPLEREQUESTEDADC 0
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R1_SAMPLEREADINGADC 0
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R1_PROCESSING 0
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R2_LCD_SEND 1
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R2_LCD 1
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R3_UART 2
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R3_UART_SEND 2
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R4_BUTTON 3
#define SCVI_STATECHART_MAIN_REGION_VYKDYMAS_R4_CHECK_BUTTONS 3
#define SCVI_STATECHART_MAIN_REGION_START 0


/* 
 * Enum of event names in the statechart.
 */
typedef enum  {
	Statechart_invalid_event = SC_INVALID_EVENT_VALUE,
	Statechart_Ev_GetSample,
	Statechart_Ev_ADCSampleReady,
	Statechart_Ev_SendUart,
	Statechart_Ev_DisplayLCD,
	Statechart_Ev_Button
} StatechartEventID;

/*
 * Struct that represents a single event.
 */
typedef struct {
	StatechartEventID name;
} statechart_event;

/*
 * Queue that holds the raised events.
 */
typedef struct statechart_eventqueue_s {
	statechart_event *events;
	sc_integer capacity;
	sc_integer pop_index;
	sc_integer push_index;
	sc_integer size;
} statechart_eventqueue;

/*! Enumeration of all states */ 
typedef enum
{
	Statechart_last_state,
	Statechart_main_region_Vykdymas,
	Statechart_main_region_Vykdymas_r1_WaitSamplePeriod,
	Statechart_main_region_Vykdymas_r1_SampleRequestedADC,
	Statechart_main_region_Vykdymas_r1_SampleReadingADC,
	Statechart_main_region_Vykdymas_r1_Processing,
	Statechart_main_region_Vykdymas_r2_LCD_Send,
	Statechart_main_region_Vykdymas_r2_LCD,
	Statechart_main_region_Vykdymas_r3_UART,
	Statechart_main_region_Vykdymas_r3_UART_Send,
	Statechart_main_region_Vykdymas_r4_Button,
	Statechart_main_region_Vykdymas_r4_Check_Buttons,
	Statechart_main_region_Start
} StatechartStates;


/*! Type declaration of the data structure for the StatechartIface interface scope. */
struct StatechartIface
{
	sc_boolean Ev_GetSample_raised;
	sc_boolean Ev_ADCSampleReady_raised;
	sc_boolean Ev_SendUart_raised;
	sc_boolean Ev_DisplayLCD_raised;
	sc_boolean Ev_Button_raised;
};



/*! Type declaration of the data structure for the StatechartInternal interface scope. */
struct StatechartInternal
{
	sc_integer sample_no;
};






/*! 
 * Type declaration of the data structure for the Statechart state machine.
 * This data structure has to be allocated by the client code. 
 */
struct Statechart
{
	StatechartStates stateConfVector[STATECHART_MAX_ORTHOGONAL_STATES];
	StatechartIface iface;
	StatechartInternal internal;
	sc_boolean completed;
	sc_boolean doCompletion;
	sc_boolean isExecuting;
	sc_integer stateConfVectorPosition;
	statechart_eventqueue in_event_queue;
	statechart_event in_buffer[STATECHART_IN_EVENTQUEUE_BUFFERSIZE];
};



/*! Initializes the Statechart state machine data structures. Must be called before first usage.*/
extern void statechart_init(Statechart* handle);


/*! Activates the state machine. */
extern void statechart_enter(Statechart* handle);

/*! Deactivates the state machine. */
extern void statechart_exit(Statechart* handle);

/*! 
Can be used by the client code to trigger a run to completion step without raising an event.
*/
extern void statechart_trigger_without_event(Statechart* handle);



/*! Raises the in event 'Ev_GetSample' that is defined in the default interface scope. */ 
extern void statechart_raise_ev_GetSample(Statechart* handle);
/*! Raises the in event 'Ev_ADCSampleReady' that is defined in the default interface scope. */ 
extern void statechart_raise_ev_ADCSampleReady(Statechart* handle);
/*! Raises the in event 'Ev_SendUart' that is defined in the default interface scope. */ 
extern void statechart_raise_ev_SendUart(Statechart* handle);
/*! Raises the in event 'Ev_DisplayLCD' that is defined in the default interface scope. */ 
extern void statechart_raise_ev_DisplayLCD(Statechart* handle);
/*! Raises the in event 'Ev_Button' that is defined in the default interface scope. */ 
extern void statechart_raise_ev_Button(Statechart* handle);

/*!
 * Checks whether the state machine is active (until 2.4.1 this method was used for states).
 * A state machine is active if it was entered. It is inactive if it has not been entered at all or if it has been exited.
 */
extern sc_boolean statechart_is_active(const Statechart* handle);

/*!
 * Checks if all active states are final. 
 * If there are no active states then the state machine is considered being inactive. In this case this method returns false.
 */
extern sc_boolean statechart_is_final(const Statechart* handle);

/*! Checks if the specified state is active (until 2.4.1 the used method for states was called isActive()). */
extern sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state);


#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_H_ */
